services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\ScriptBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaScriptBundle.php'
